name: mps-forecasting
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - scipy=1.5.2
  - joblib=0.17.0
  - matplotlib=3.3.2
  - pystan=2.19.1.1
  - arviz=0.6.1
  - pandas=1.1.3
  - ipython=7.18.1
  - xlrd=1.2.0
  - seaborn-0.11.0
